# Generated by Django 4.1 on 2023-10-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0005_alter_additionalprofile_uniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalprofile',
            name='uniqueid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
