# Generated by Django 4.1 on 2023-10-13 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0006_alter_additionalprofile_uniqueid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='resume_uploads/')),
            ],
        ),
        migrations.AddField(
            model_name='additionalprofile',
            name='templateid',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='education_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resume.additionalprofile'),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='started_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='stopped_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resume.additionalprofile'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='achievement',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='company',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='job_title',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='started_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='stopped_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='work_experience_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resume.additionalprofile'),
        ),
    ]
